### ISSUE TITLE
Building Bixler fails

### ISSUE THREAD

**Issue by MJafarMashhadi** [MJafarMashhadi/pprz_tester#1]
```
python pprz_tester/run_test.py --build --gcs Bixler

make: Entering directory '/home/ict520c/Documents/paparazzi'
-----------------------------------------------------------------------
Paparazzi version v5.15_devel-229-g3fb4ee4d5-dirty
-----------------------------------------------------------------------
#######################################
# BUILD AIRCRAFT=Bixler, TARGET nps
#######################################
make[1]: Entering directory '/home/ict520c/Documents/paparazzi'
GENERATE /home/ict520c/Documents/paparazzi/var/aircrafts/Bixler/nps/generated/radio.h from radios/cockpitSX.xml
make[1]: Leaving directory '/home/ict520c/Documents/paparazzi'
make[1]: Entering directory '/home/ict520c/Documents/paparazzi'
GENERATE /home/ict520c/Documents/paparazzi/var/aircrafts/Bixler/nps/generated/flight_plan.h from flight_plans/versatile.xml
No SRTM data found to check altitude.
NOTICE: low altitude (185<185+25) in <waypoint Y="20.0" X="80.0" NAME="TD" ALT="185.0"/>
GENERATE /home/ict520c/Documents/paparazzi/var/aircrafts/Bixler/flight_plan.xml from flight_plans/versatile.xml
make[1]: Leaving directory '/home/ict520c/Documents/paparazzi'
make[1]: Entering directory '/home/ict520c/Documents/paparazzi'
GENERATE /home/ict520c/Documents/paparazzi/var/aircrafts/Bixler/nps/generated/airframe.h from airframes/examples/bixler_lisa_m_2.xml
GENERATE autopilots in /home/ict520c/Documents/paparazzi/var/aircrafts/Bixler/nps/generated/
GENERATE /home/ict520c/Documents/paparazzi/var/aircrafts/Bixler/nps/generated/modules.h
GENERATE /home/ict520c/Documents/paparazzi/var/aircrafts/Bixler/nps/generated/periodic_telemetry.h from telemetry/default_fixedwing_imu.xml
GENERATE /home/ict520c/Documents/paparazzi/var/aircrafts/Bixler/nps/generated/settings.h
make[1]: Leaving directory '/home/ict520c/Documents/paparazzi'
Info: module 'imu_common.xml' has been loaded several times for target ap, merging options
Info: module 'gps.xml' has been loaded several times for target ap, merging options
Info: module 'gps.xml' has been loaded several times for target sim, merging options
Info: module 'imu_common.xml' has been loaded several times for target nps, merging options
Info: module 'gps.xml' has been loaded several times for target nps, merging options
cd sw/airborne; make -j8 TARGET=nps all
make[1]: Entering directory '/home/ict520c/Documents/paparazzi/sw/airborne'
Paparazzi jsbsim package found: yes
CC /home/ict520c/Documents/paparazzi/var/aircrafts/Bixler/nps/mcu.o
CC /home/ict520c/Documents/paparazzi/var/aircrafts/Bixler/nps/arch/sim/mcu_arch.o
CC /home/ict520c/Documents/paparazzi/var/aircrafts/Bixler/nps/mcu_periph/sys_time.o
cc: error trying to exec 'cc1': execvp: No such file or directory
/home/ict520c/Documents/paparazzi/conf/Makefile.nps:109: recipe for target '/home/ict520c/Documents/paparazzi/var/aircrafts/Bixler/nps/mcu.o' failed
make[1]: *** [/home/ict520c/Documents/paparazzi/var/aircrafts/Bixler/nps/mcu.o] Error 1
make[1]: *** Waiting for unfinished jobs....
cc: error trying to exec 'cc1': execvp: No such file or directory
/home/ict520c/Documents/paparazzi/conf/Makefile.nps:109: recipe for target '/home/ict520c/Documents/paparazzi/var/aircrafts/Bixler/nps/arch/sim/mcu_arch.o' failed
make[1]: *** [/home/ict520c/Documents/paparazzi/var/aircrafts/Bixler/nps/arch/sim/mcu_arch.o] Error 1
cc: error trying to exec 'cc1': execvp: No such file or directory
/home/ict520c/Documents/paparazzi/conf/Makefile.nps:109: recipe for target '/home/ict520c/Documents/paparazzi/var/aircrafts/Bixler/nps/mcu_periph/sys_time.o' failed
make[1]: *** [/home/ict520c/Documents/paparazzi/var/aircrafts/Bixler/nps/mcu_periph/sys_time.o] Error 1
make[1]: *** wait: No child processes.  Stop.
Makefile.ac:310: recipe for target 'nps.compile' failed
make: *** [nps.compile] Error 2
make: Leaving directory '/home/ict520c/Documents/paparazzi'
Traceback (most recent call last):
  File "pprz_tester/run_test.py", line 131, in <module>
    build()
  File "pprz_tester/run_test.py", line 80, in build
    build = subprocess.check_call(command, env={
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-C', '/home/ict520c/Documents/paparazzi', '-f', 'Makefile.ac', 'AIRCRAFT=Bixler', 'nps.compile']' returned non-zero exit status 2.

```

**Comment by MJafarMashhadi** [comment]
Now `Microjet` fails too. Great.
